[build]
providers = ["python"]

[build.nixPkgs]
pkgs = ["python311", "zbar"]

[build.nixLibs]
libs = ["zbar"]

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
